twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
        - form/fields.html.twig
    paths:
        'assets/images': images
        'assets/styles': css

#    globals:
#        parsedown: "@parsedown"

when@test:
    twig:
        strict_variables: true
